stocks:
- symbol: IWDA.LON
  firstTransaction: "2021-03-11"
- symbol: CSPX.LON
  first_transaction: "2021-03-29"

downloadConfig:
  maxTriesBeforeEndOfTrading: 30
  outputSize: full
  dateFormat: "YYYY-MM-DD"

questDb:
  minConnections: 3
  maxConnections: 10
  user: admin
  password: quest
  host: "127.0.0.1"
  port: "8812"
  database: qdb
