stocks:
- symbol: IWDA.LON
  firstTransaction: "2021-03-11"
  api: Alphavantage
  currency: USD
- symbol: CSPX.LON
  first_transaction: "2021-03-29"
  api: Alphavantage
  currency: USD
- symbol: MBH.SI
  first_transaction: "2021-04-04"
  api: Yahoo
  currency: SGD

downloadConfig:
  maxTriesBeforeEndOfTrading: 30
  dateFormat: "YYYY-MM-DD"
  batchSizeForPersistence: 20
  alphavantageOutputSize: full
  yahooPeriod: max

timescaleDb:
  minConnections: 5
  maxConnections: 20
  user: postgres
  password: password
  host: "127.0.0.1"
  port: "5432"
  database: postgres

currency:
  baseCurrency: USD
  otherCurrencies:
  - currency: SGD
    firstTransaction: "2021-04-04"
