stocks:
- symbol: IWDA.LON
  firstTransaction: "2021-03-11"
- symbol: CSPX.LON
  first_transaction: "2021-03-29"

downloadConfig:
  maxTriesBeforeEndOfTrading: 30
  outputSize: full
  dateFormat: "YYYY-MM-DD"
  batchSizeForPersistence: 20

timescaleDb:
  minConnections: 5
  maxConnections: 20
  user: postgres
  password: password
  host: "127.0.0.1"
  port: "5432"
  database: postgres
